version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
